version: "3"
services:
  mysql:
    build:
      context: "./mysql"
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/app"
      - "${MYSQL_PATH}/my.cnf:/etc/mysql/my.cnf"
    ports:
      - "${MYSQL_PORT}:3306"
  monica:
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/monica
    build:
      context: ./monica
    env_file:
      - .env_dev
    ports:
      - ${MONICA_PORT}:80
  
  phpmyadmin:
    build: "./phpmyadmin"
    environment:
      - "PMA_ARBITRARY=1"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    ports:
      - "${PMA_PORT}:80"
volumes:
  phpmyadmin:
    driver: "${VOLUMES_DRIVER}"

